/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=dev --include-runtime=false worker/worker-configuration.d.ts` (hash: be9b7a7d0da658380d91109f2addd991)
interface __BaseEnv_Env {
	SUBMISSION_RATE_LIMITER: RateLimit;
	REPORT_RATE_LIMITER: RateLimit;
	LOGIN_RATE_LIMITER: RateLimit;
	TRACKING_RATE_LIMITER: RateLimit;
	ENVIRONMENT: "test";
	GITHUB_DATA_REPOSITORY: "PerkCommons/data";
	GITHUB_DATA_BRANCH: "main";
	GITHUB_HEAD_OWNER: "PerkCommons";
	GITHUB_SITE_REPOSITORY: "PerkCommons/site";
	FORK_ONLY_MODE: "false";
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUBMISSION_FINGERPRINT_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENVIRONMENT" | "GITHUB_DATA_REPOSITORY" | "GITHUB_DATA_BRANCH" | "GITHUB_HEAD_OWNER" | "GITHUB_SITE_REPOSITORY" | "FORK_ONLY_MODE" | "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY" | "SUPABASE_SERVICE_ROLE_KEY" | "SUBMISSION_FINGERPRINT_SECRET">> {}
}
